<?php
	if($statecode==1){
		$state="Alabama";
	}
	elseif($statecode==2){
		$state="Alaska";
	}
	elseif($statecode==3){
		$state="Arizona";
	}
	elseif($statecode==4){
		$state="Arkansas";
	}
	elseif($statecode==5){
		$state="California";
	}
	elseif($statecode==6){
		$state="Colorado";
	}
	elseif($statecode==7){
		$state="Connecticut";
	}
	elseif($statecode==8){
		$state="Delaware";
	}
	elseif($statecode==9){
		$state="Florida";
	}
	elseif($statecode==10){
		$state="Georgia";
	}
	elseif($statecode==11){
		$state="Hawaii";
	}
	elseif($statecode==12){
		$state="Idaho";
	}
	elseif($statecode==13){
		$state="Illinois";
	}
	elseif($statecode==14){
		$state="Indiana";
	}
	elseif($statecode==15){
		$state="Iowa";
	}
	elseif($statecode==16){
		$state="Kansas";
	}
	elseif($statecode==17){
		$state="Kentucky";
	}
	elseif($statecode==18){
		$state="Louisiana";
	}
	elseif($statecode==19){
		$state="Maine";
	}
	elseif($statecode==20){
		$state="Maryland";
	}
	elseif($statecode==21){
		$state="Massachusettes";
	}
	elseif($statecode==22){
		$state="Michigan";
	}
	elseif($statecode==23){
		$state="Minnesota";
	}
	elseif($statecode==24){
		$state="Mississippi";
	}
	elseif($statecode==25){
		$state="Missouri";
	}
	elseif($statecode==26){
		$state="Montana";
	}
	elseif($statecode==27){
		$state="Nebraska";
	}
	elseif($statecode==28){
		$state="Nevada";
	}
	elseif($statecode==29){
		$state="New Hampshire";
	}
	elseif($statecode==30){
		$state="New Jersey";
	}
	elseif($statecode==31){
		$state="New Mexico";
	}
	elseif($statecode==32){
		$state="New York";
	}
	elseif($statecode==33){
		$state="North Carolina";
	}
	elseif($statecode==34){
		$state="North Dakota";
	}
	elseif($statecode==35){
		$state="Ohio";
	}
	elseif($statecode==36){
		$state="Oklahoma";
	}
	elseif($statecode==37){
		$state="Oregon";
	}
	elseif($statecode==38){
		$state="Pennsylvania";
	}
	elseif($statecode==39){
		$state="Rhode Island";
	}
	elseif($statecode==40){
		$state="South Carolina";
	}
	elseif($statecode==41){
		$state="South Dakota";
	}
	elseif($statecode==42){
		$state="Tennesse";
	}
	elseif($statecode==43){
		$state="Texas";
	}
	elseif($statecode==44){
		$state="Utah";
	}
	elseif($statecode==45){
		$state="Vermont";
	}
	elseif($statecode==46){
		$state="Virginia";
	}
	elseif($statecode==47){
		$state="Washington";
	}
	elseif($statecode==48){
		$state="West Virginia";
	}
	elseif($statecode==49){
		$state="Wisconsin";
	}
	elseif($statecode==50){
		$state="Wyoming";
	}
	else{
		$state="Error";
	}
?>